---
title: "Reorder Analysis"
author: "Lisa Li"
date: "2/23/2021"
output: html_document
---

# Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
```

# Load Libraries
```{r Load Libraries}
library(RPostgreSQL)
library(dplyr)
library(dbplyr)
library(data.table)
library(lubridate)
library(reshape2)
library(stringr)
library(readxl)
library(writexl)
library(openxlsx)
library(tidyverse)
library(odbc)
```

# Database Connection and Data Loading
```{r Data Loading}
# Establishing connection to SQL Server
con_sql <- DBI::dbConnect(odbc::odbc(),
                          Driver   = "SQL Server",
                          Server   = "<server_ip>",
                          Database = "PROCUREMENTDB",
                          UID      = "<user_id>",
                          PWD      = "<password>",
                          Port     = 1433)

# Fetching data from various SQL queries
inventory_report <- DBI::dbGetQuery(con_sql, "SELECT I.item_no, I.whse_code, SUM(I.instock_inventory) AS instock_inventory FROM PROCUREMENTDB.Retail.InventoryReportView I GROUP BY I.item_no, I.whse_code")
opendemand_report <- DBI::dbGetQuery(con_sql, "SELECT Isbn, SUM(OpenQuantity) AS Open_Quantity FROM PROCUREMENTDB.Retail.OpenQuantityView GROUP BY Isbn")
sku_list <- DBI::dbGetQuery(con_sql, "SELECT * FROM Retail.SkuCategoryPriceView")
fifo_data <- DBI::dbGetQuery(con_sql, "SELECT MAX(F.FIFO) AS FIFO, F.ISBN AS item_no FROM PROCUREMENTDB.Retail.FIFO F GROUP BY F.ISBN")
```

# Business Report Cleaning
```{r Business Report Cleaning}
# Reading and cleaning the business report
sku_orders_adhoc_all <- read.csv("<path_to_csv>/BusinessReport-2-23-21.csv")
sku_orders_adhoc_all <- sku_orders_adhoc_all %>% 
  mutate(across(where(is.character), ~as.numeric(gsub("[/$,]", "", .x))))

# Sum of total orders
total_orders <- sum(sku_orders_adhoc_all$Units.Ordered, na.rm = TRUE)
```

# Data Sources Cleaning
```{r Data Sources Cleaning}
# Transforming and cleaning inventory report
inventory_report <- inventory_report %>%
  pivot_wider(names_from = whse_code, values_from = instock_inventory, values_fill = list(instock_inventory = 0)) %>%
  mutate(Amazon_Instock = FBA_AW + FBA_TR,
         Warehouse_Instock= AW + FBM + TB + `TB-2` + TR,
         Instock_Inventory = Amazon_Instock + Warehouse_Instock) %>%
  select(item_no, Instock_Inventory, Warehouse_Instock, Amazon_Instock)
```

# Sale Data Information Combination
```{r Sale Data Combination}
# Combining SKU list with orders data
combined_data <- sku_orders_adhoc_all %>%
  group_by(SKU) %>%
  summarize(across(Sessions:Buy.Box.Percentage, sum, na.rm = TRUE), .groups = 'drop') %>%
  left_join(sku_list, by = c("SKU" = "Sku")) %>%
  rename_with(~str_replace(., "\\.", "_"), everything()) %>%
  filter(!is.na(Isbn))

# Joining with inventory report and open demand report
sku_velocity <- combined_data %>%
  full_join(inventory_report, by = c("Isbn" = "item_no")) %>%
  left_join(opendemand_report, by = "Isbn") %>%
  replace_na(list(across(everything(), ~0)))
```

# Final Data Cleaning and Writing
```{r Final Data Cleaning and Writing}
# Aggregating and cleaning the final data
isbn_velocity <- sku_velocity %>%
  group_by(Isbn) %>%
  summarize(across(Amz_Pageviews:Open_Quantity, sum, na.rm = TRUE), 
            Velocity = sum(Amz_Units)/7,
            Excess_Qty = (sum(Instock_Inventory) + sum(Open_Quantity)) - sum(Amz_Units)/7*90,
            .groups = 'drop') %>%
  left_join(fifo_data, by = c("Isbn" = "item_no")) %>%
  replace_na(list(FIFO = 0))

# Writing the final data to Excel
output_path <- "<path_to_output>/Reorder Analysis_2021-02-23.xlsx"
write.xlsx(isbn_velocity,

 sheetName = "Reorder Analysis", output_path)
```
